keys:
  - &macbook-air age15xehrktetsnjql535g3nfsu6vxzx93z3pn900jmf7slvzk6s5dwsg982wh

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *macbook-air
  - path_regex: secrets/[^/]+\.json$
    key_groups:
      - age:
          - *macbook-air
