---
name: Test Flake

on:
  pull_request:

permissions: {}

jobs:
  tests:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@9280e7aca88deada44c930f1e2c78e21c3ae3edd # v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup CI cache
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13
        with:
          diagnostic-endpoint: ""

      - name: Setup devenv cache
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: devenv

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@3164002371bc90729c68af0e24d5aacf20d7c9f6 # v12
        with:
          send-statistics: false

      - name: Install devenv
        run: nix profile add nixpkgs#devenv

      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test
