---
name: Test Flake

on:
  pull_request:

permissions: {}

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup CI cache
        uses: DeterminateSystems/magic-nix-cache-action@v13
        with:
          diagnostic-endpoint: ""

      - name: Setup devenv cache
        uses: cachix/cachix-action@v15
        with:
          name: devenv

      - name: Install devenv
        run: nix profile add nixpkgs#devenv

      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test
