---
name: Test Flake

on:
  pull_request:

permissions: {}

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v20
        with:
          diagnostic-endpoint: ""

      - name: Setup cache
        uses: DeterminateSystems/magic-nix-cache-action@v13
        with:
          diagnostic-endpoint: ""

      - name: Install devenv
        run: nix profile install nixpkgs#devenv

      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test
